/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kernel.Dentista;

/**
 *
 * @author home
 */
public class CadDentista extends javax.swing.JInternalFrame {
    Dentista dente;
    
    
    /**
     * Creates new form CadDentista
     */
    public CadDentista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpCadDentista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jftCPF = new javax.swing.JFormattedTextField();
        jftTelefone = new javax.swing.JFormattedTextField();
        jtEmail = new javax.swing.JTextField();
        jtFatorRH = new javax.swing.JTextField();
        jpCadDentistaEndereco = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jtNumber = new javax.swing.JTextField();
        jtComplemento = new javax.swing.JTextField();
        jtBairro = new javax.swing.JTextField();
        jtCidade = new javax.swing.JTextField();
        jtEstado = new javax.swing.JTextField();
        jtPais = new javax.swing.JTextField();
        jftDataNascimento = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jtCRO = new javax.swing.JTextField();
        jbtCancelar = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Dentista");
        setMinimumSize(new java.awt.Dimension(720, 460));

        jpCadDentista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Dentista - Informações Pessoais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Nome: ");

        jLabel2.setText("CPF: ");

        jLabel3.setText("Telefone:");

        jLabel4.setText("E-mail: ");

        jLabel5.setText("Data de Nascimento:");

        jLabel6.setText("Tipo Sanguineo: ");

        jtNome.setToolTipText("Digite o nome completo");

        try {
            jftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCPF.setToolTipText("Informe o CPF");

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setToolTipText("Informe o telefone de contato");

        jtEmail.setToolTipText("Informe o e-mail de contato");

        jpCadDentistaEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel7.setText("Logradouro:");

        jLabel8.setText("Número: ");

        jLabel9.setText("Complemento: ");

        jLabel10.setText("CEP: ");

        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEP.setToolTipText("Informe o CEP");

        jLabel11.setText("Bairro: ");

        jLabel12.setText("Cidade: ");

        jLabel13.setText("Estado: ");

        jLabel14.setText("País: ");

        jtRua.setToolTipText("Informe o endereço");

        jtNumber.setToolTipText("Informe o número do imóvel");

        jtComplemento.setToolTipText("Informe o complemento - Se necessário");

        jtBairro.setToolTipText("Informe o bairro");

        jtCidade.setToolTipText("Informe a cidade");

        jtEstado.setToolTipText("Informe o estado");

        jtPais.setText("BRASIL");
        jtPais.setToolTipText("Informe o país");

        javax.swing.GroupLayout jpCadDentistaEnderecoLayout = new javax.swing.GroupLayout(jpCadDentistaEndereco);
        jpCadDentistaEndereco.setLayout(jpCadDentistaEnderecoLayout);
        jpCadDentistaEnderecoLayout.setHorizontalGroup(
            jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadDentistaEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadDentistaEnderecoLayout.createSequentialGroup()
                        .addGroup(jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadDentistaEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtRua))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadDentistaEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEstado)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpCadDentistaEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCadDentistaEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtBairro)))
                .addGap(41, 41, 41))
        );
        jpCadDentistaEnderecoLayout.setVerticalGroup(
            jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadDentistaEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadDentistaEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        try {
            jftDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataNascimento.setToolTipText("Informe a data de nascimento - Utilize o formato: DD/MM/AAAA");

        jLabel15.setText("CRO: ");

        javax.swing.GroupLayout jpCadDentistaLayout = new javax.swing.GroupLayout(jpCadDentista);
        jpCadDentista.setLayout(jpCadDentistaLayout);
        jpCadDentistaLayout.setHorizontalGroup(
            jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadDentistaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCadDentistaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadDentistaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEmail)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtFatorRH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadDentistaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCRO)))
                .addGap(0, 46, Short.MAX_VALUE))
            .addComponent(jpCadDentistaEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpCadDentistaLayout.setVerticalGroup(
            jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadDentistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jtCRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jpCadDentistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jtFatorRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jpCadDentistaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jpCadDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCadDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        // Função do botão cancelar
        int escolha = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar?", "Cancelar",JOptionPane.YES_NO_OPTION);
        if(escolha == JOptionPane.YES_OPTION){
            limparCampos(); 
        }else{

        }//fim do else
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        // Função do botão Salvar
        
        if(validaCampos()){ //PRIMEIRAMENTE VERIFICA SE TODOS OS CAMPOS ESTÃO PREENCHIDOS
            preencheObjD();
            JOptionPane.showMessageDialog(this, "Profissional cadastrado com sucesso!");
        }    
         
        //limparCampos();
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JFormattedTextField jftDataNascimento;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JPanel jpCadDentista;
    private javax.swing.JPanel jpCadDentistaEndereco;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCRO;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtFatorRH;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumber;
    private javax.swing.JTextField jtPais;
    private javax.swing.JTextField jtRua;
    // End of variables declaration//GEN-END:variables

/*
    Este método tem a função de preencher o objeto com os valores informados no formulário
*/
public void preencheObjD(){
    ArrayList<Dentista> listaDentista = new ArrayList();
    dente = new Dentista();
    
    dente.setNome(jtNome.getText());
    dente.setCro(Integer.parseInt(jtCRO.getText()));
    dente.setCPF(jftCPF.getText());
    dente.setTelefone(jftTelefone.getText());
    dente.setDataNascimento(jftDataNascimento.getText());
    dente.setEmail(jtEmail.getText());
    dente.setFatorRH(jtFatorRH.getText());
    dente.setEndereco(jtRua.getText(), Integer.parseInt(jtNumber.getText()) , jtComplemento.getText(), jtBairro.getText(),
            jftCEP.getText(), jtCidade.getText(), jtEstado.getText(), jtPais.getText());
    
    
    listaDentista.add(dente);
}

/*
    Este método tem a função de verificar se todos os campos foram preenchidos.
*/
private boolean validaCampos(){
    if(jtNome.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Nome");
        jtNome.requestFocus();
        return false;
    }
    if(jtCRO.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o CRO");
        jtCRO.requestFocus();
        return false;
    }
    if(jftCPF.getText().length() < 14 || jftCPF.getText().length() > 14 ){
        JOptionPane.showMessageDialog(this, "CPF inválido");
        jftCPF.requestFocus();
        return false;
    }
    if(jftTelefone.getText().length() < 12 || jftTelefone.getText().length() > 13 ){
        JOptionPane.showMessageDialog(this, "Número de telefone inválido");
        jftTelefone.requestFocus();
        return false;
    }
    if(jftDataNascimento.getText().length() < 10 || jftDataNascimento.getText().length() > 10 ){
        JOptionPane.showMessageDialog(this, "Data de nascimento inválida");
        jftDataNascimento.requestFocus();
        return false;
    }
    if(jtEmail.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o E-mail");
        jtEmail.requestFocus();
        return false;
    }
    if(jtFatorRH.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Tipo Sanguineo");
        jtFatorRH.requestFocus();
        return false;
    }
    //VALIDA CAMPOS DE ENDEREÇO <!-- CAMPO COMPLEMENTO É OPCIONAL -->
    if(jtRua.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Logradouro");
        jtRua.requestFocus();
        return false;
    }
    if(jtNumber.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Número");
        jtNumber.requestFocus();
        return false;
    }
    if(jftCEP.getText().length() < 9 || jftCEP.getText().length() > 9 ){
        JOptionPane.showMessageDialog(this, "Informe o CEP do logradouro");
        jftCEP.requestFocus();
        return false;
    }
    if(jtBairro.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Bairro");
        jtBairro.requestFocus();
        return false;
    }
    if(jtCidade.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe a Cidade");
        jtCidade.requestFocus();
        return false;
    }
    if(jtEstado.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o Estado");
        jtEstado.requestFocus();
        return false;
    }
    if(jtPais.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o País");
        jtPais.requestFocus();
        return false;
    }
    
    return true;
}

/*
    Este método tem a função de limpar os campos após realizar a tarefa requisitada onde este foi implementado
*/
private void limparCampos(){
    //Dados Profissionais
    jtNome.setText("");
    jtCRO.setText("");
    jftCPF.setText("");
    jftTelefone.setText("");
    jftDataNascimento.setText("");
    jtEmail.setText("");
    jtFatorRH.setText("");
    //Dados de endereço
    jtRua.setText("");
    jtNumber.setText("");
    jtComplemento.setText("");
    jftCEP.setText("");
    jtBairro.setText("");
    jtCidade.setText("");
    jtEstado.setText("");
    jtPais.setText("");
}//fim do método limpar campos

}
