/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import javax.swing.JOptionPane;
import kernel.Paciente;

/**
 *
 * @author home
 */
public class CadPaciente extends javax.swing.JInternalFrame {
    Paciente cli;
    /**
     * Creates new form CadPaciente
     */
    public CadPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoDiabetes = new javax.swing.ButtonGroup();
        btnGrupoHipertenso = new javax.swing.ButtonGroup();
        btnGrupoHemofilico = new javax.swing.ButtonGroup();
        btnGrupoFumante = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jftNascimento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jftCPF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtFatorRH = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtComplemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jftCEP = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jtBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtEstado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtPais = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jrbSIMDiabetes = new javax.swing.JRadioButton();
        jrbNAODiabetes = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jrbSIMHipertenso = new javax.swing.JRadioButton();
        jrbNAOHipertenso = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jrbSIMHemofilia = new javax.swing.JRadioButton();
        jrbNAOHemofilia = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jrbSIMFumante = new javax.swing.JRadioButton();
        jrbNAOFumante = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jcbTratamentoMedico = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jcbGravida = new javax.swing.JComboBox();
        jbtCancelar = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro Paciente");

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Paciente - Informações Pessoais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setText("Nome: ");

        jtNome.setToolTipText("Informe o nome do paciente");

        jLabel2.setText("Data de Nascimento: ");

        try {
            jftNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftNascimento.setToolTipText("Informe a data de nascimento");

        jLabel3.setText("CPF: ");

        try {
            jftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCPF.setToolTipText("Informe o CPF");

        jLabel4.setText("Telefone: ");

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setToolTipText("Informe o número de telefone");

        jLabel5.setText("Tipo Sanguineo: ");

        jtFatorRH.setToolTipText("Informe o tipo sanguíneo");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel6.setText("Logradouro: ");

        jtRua.setToolTipText("Informe o logradouro");

        jLabel7.setText("Número: ");

        jtNumber.setToolTipText("Informe o número do imóvel");

        jLabel8.setText("Complemento: ");

        jtComplemento.setToolTipText("Informe o complemento, caso necessário");

        jLabel9.setText("CEP: ");

        try {
            jftCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCEP.setToolTipText("Informe o CEP");

        jLabel10.setText("Bairro:");

        jtBairro.setToolTipText("Informe o bairro");

        jLabel11.setText("Cidade: ");

        jtCidade.setToolTipText("Informe a cidade");

        jLabel12.setText("Estado: ");

        jtEstado.setToolTipText("Informe o estado");

        jLabel13.setText("País: ");

        jtPais.setText("BRASIL");
        jtPais.setToolTipText("Informe o país");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNumber))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtBairro))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPais)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jftCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel20.setText("E-mail: ");

        jtEmail.setToolTipText("Informe o e-mail");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtFatorRH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtFatorRH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Informações Pessoais", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ficha Clínica", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel14.setText("Diabetes: ");

        btnGrupoDiabetes.add(jrbSIMDiabetes);
        jrbSIMDiabetes.setText("SIM");

        btnGrupoDiabetes.add(jrbNAODiabetes);
        jrbNAODiabetes.setText("NÃO");

        jLabel15.setText("Hipertensão: ");

        btnGrupoHipertenso.add(jrbSIMHipertenso);
        jrbSIMHipertenso.setText("SIM");

        btnGrupoHipertenso.add(jrbNAOHipertenso);
        jrbNAOHipertenso.setText("NÃO");

        jLabel16.setText("Hemofilia: ");

        btnGrupoHemofilico.add(jrbSIMHemofilia);
        jrbSIMHemofilia.setText("SIM");

        btnGrupoHemofilico.add(jrbNAOHemofilia);
        jrbNAOHemofilia.setText("NÃO");

        jLabel17.setText("Fumante: ");

        btnGrupoFumante.add(jrbSIMFumante);
        jrbSIMFumante.setText("SIM");

        btnGrupoFumante.add(jrbNAOFumante);
        jrbNAOFumante.setText("NÃO");

        jLabel18.setText("Tratamento Médico: ");

        jcbTratamentoMedico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "SIM", "NÃO" }));

        jLabel19.setText("Grávida ou lactante: ");

        jcbGravida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "SIM", "NÃO" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTratamentoMedico, 0, 130, Short.MAX_VALUE)
                            .addComponent(jcbGravida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbSIMDiabetes)
                            .addGap(18, 18, 18)
                            .addComponent(jrbNAODiabetes))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jrbSIMHemofilia)
                                    .addGap(18, 18, 18)
                                    .addComponent(jrbNAOHemofilia))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jrbSIMHipertenso)
                                    .addGap(18, 18, 18)
                                    .addComponent(jrbNAOHipertenso))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jrbSIMFumante)
                                    .addGap(18, 18, 18)
                                    .addComponent(jrbNAOFumante))))))
                .addGap(128, 445, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jrbSIMDiabetes)
                    .addComponent(jrbNAODiabetes))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jrbSIMHipertenso)
                    .addComponent(jrbNAOHipertenso))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jrbSIMHemofilia)
                    .addComponent(jrbNAOHemofilia))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jrbSIMFumante)
                    .addComponent(jrbNAOFumante))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jcbTratamentoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbGravida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ficha Clínica", jPanel3);

        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jbtSalvar.setText("Salvar");
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar Campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        // Função do botão cancelar
        int escolha = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar?", "Cancelar",JOptionPane.YES_NO_OPTION);
        if(escolha == JOptionPane.YES_OPTION){
            limparCampos(); 
        }else{

        }//fim do else
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed
        // TODO add your handling code here:
        if(validaCampos()){//se os campos estiverem todos preenchidos o código abaixo será executado
            preencheObj();
            JOptionPane.showMessageDialog(this, "Profissional cadastrado com sucesso!");
        }
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupoDiabetes;
    private javax.swing.ButtonGroup btnGrupoFumante;
    private javax.swing.ButtonGroup btnGrupoHemofilico;
    private javax.swing.ButtonGroup btnGrupoHipertenso;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JComboBox jcbGravida;
    private javax.swing.JComboBox jcbTratamentoMedico;
    private javax.swing.JFormattedTextField jftCEP;
    private javax.swing.JFormattedTextField jftCPF;
    private javax.swing.JFormattedTextField jftNascimento;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JRadioButton jrbNAODiabetes;
    private javax.swing.JRadioButton jrbNAOFumante;
    private javax.swing.JRadioButton jrbNAOHemofilia;
    private javax.swing.JRadioButton jrbNAOHipertenso;
    private javax.swing.JRadioButton jrbSIMDiabetes;
    private javax.swing.JRadioButton jrbSIMFumante;
    private javax.swing.JRadioButton jrbSIMHemofilia;
    private javax.swing.JRadioButton jrbSIMHipertenso;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtCidade;
    private javax.swing.JTextField jtComplemento;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtFatorRH;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNumber;
    private javax.swing.JTextField jtPais;
    private javax.swing.JTextField jtRua;
    // End of variables declaration//GEN-END:variables

private void limparCampos(){
    //Dados Profissionais
    jtNome.setText("");
    jftCPF.setText("");
    jftTelefone.setText("");
    jftNascimento.setText("");
    jtEmail.setText("");
    jtFatorRH.setText("");
    //Dados de endereço
    jtRua.setText("");
    jtNumber.setText("");
    jtComplemento.setText("");
    jftCEP.setText("");
    jtBairro.setText("");
    jtCidade.setText("");
    jtEstado.setText("");
    jtPais.setText("");
    //Limpa os Button Radio
    btnGrupoDiabetes.clearSelection();
    btnGrupoFumante.clearSelection();
    btnGrupoHemofilico.clearSelection();
    btnGrupoHipertenso.clearSelection();
    //Limpa os combo box
    jcbGravida.setSelectedIndex(0);
    jcbTratamentoMedico.setSelectedIndex(0);
}

private boolean validaCampos(){
    /**
     * verifica se os dado pessoais foram preenchidos
     */
    if(jtNome.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o nome do paciente");
        jtNome.requestFocus();
        return false;
    }
    if(jftCPF.getText().length() < 14 || jftCPF.getText().length() > 14 ){
        JOptionPane.showMessageDialog(this, "CPF inválido");
        jftCPF.requestFocus();
        return false;
    }
    if(jftTelefone.getText().length() < 12 || jftTelefone.getText().length() > 13 ){
        JOptionPane.showMessageDialog(this, "Número de telefone inválido");
        jftTelefone.requestFocus();
        return false;
    }
    if(jftNascimento.getText().length() < 10 || jftNascimento.getText().length() > 10 ){
        JOptionPane.showMessageDialog(this, "Data de nascimento inválida");
        jftNascimento.requestFocus();
        return false;
    }
    if(jtEmail.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o e-mail de contato do paciente");
        jtEmail.requestFocus();
        return false;
    }
    if(jtFatorRH.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o tipo sanguíneo do paciente");
        jtFatorRH.requestFocus();
        return false;
    }
    /* @
    * Válida os campos de endereço
    *
    *******************************/
    if(jtRua.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o logradouro do paciente"
            + "\nExemplo: Rua, Avenida, Estrada, Travessa, etc...");
        jtRua.requestFocus();
        return false;
    }
    if(jtNumber.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o número do imóvel do paciente");
        jtNumber.requestFocus();
        return false;
    }
    if(jftCEP.getText().length() < 9 || jftCEP.getText().length() > 9 ){
        JOptionPane.showMessageDialog(this, "Informe o CEP do logradouro");
        jftCEP.requestFocus();
        return false;
    }
    if(jtBairro.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o bairro do paciente");
        jtBairro.requestFocus();
        return false;
    }
    if(jtCidade.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe a cidade do paciente");
        jtCidade.requestFocus();
        return false;
    }
    if(jtEstado.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o estado do paciente");
        jtEstado.requestFocus();
        return false;
    }
    if(jtPais.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Informe o país do paciente");
        jtPais.requestFocus();
        return false;
    }
    /**
     * Valida os RadioButton's
     * 
     */
    if(!jrbSIMDiabetes.isSelected() || !jrbNAODiabetes.isSelected()){
        JOptionPane.showMessageDialog(this, "Selecione se possui diabetes");
        
        return false;
    }
    if(!jrbSIMFumante.isSelected() || !jrbNAOFumante.isSelected()){
        JOptionPane.showMessageDialog(this, "Selecione se é fumante");
        
        return false;
    }
    if(!jrbSIMHemofilia.isSelected() || !jrbNAOHemofilia.isSelected()){
        JOptionPane.showMessageDialog(this, "Selecione se possui hemofilia");
        
        return false;
    }
    if(!jrbSIMHipertenso.isSelected() || !jrbNAOHipertenso.isSelected()){
        JOptionPane.showMessageDialog(this, "Selecione se possui hipertensão");
        
        return false;
    }
    /**
     * Verifica se os combo box foram selecionados corretamente
     */
    if(jcbTratamentoMedico.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(this, "Informe se o paciente encontra-se em tratamento médico");
        
        return false;
    }
    if(jcbGravida.getSelectedIndex() == 0){
        JOptionPane.showMessageDialog(this, "Informe se a paciente encontra-se grávida ou amamentando");
        
        return false;
    }
    return true;
}

public void preencheObj(){
    cli.setNome(jtNome.getText());
    cli.setCPF(jftCPF.getText());
    cli.setTelefone(jftTelefone.getText());
    cli.setDataNascimento(jftNascimento.getText());
    cli.setEmail(jtEmail.getText());
    cli.setFatorRH(jtFatorRH.getText());
    cli.setEndereco(jtRua.getText(), Integer.parseInt(jtNumber.getText()), jtComplemento.getText(), jtBairro.getText(),
            jftCEP.getText(), jtCidade.getText(), jtEstado.getText(), jtPais.getText());
    cli.setFicha(null);
}






}
